[package]
name = "sum_of_best_nonubsplit_segments"
version = "0.1.0"
authors = ["Chris Cenotti <chris.cenotti+dev@gmail.com>>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmltree = "*"
time = "0.2.*"